# Generated by Django 4.1.3 on 2022-11-19 08:15

from urllib.parse import urlparse

import django.utils.timezone
from django.db import migrations, models


def forward(apps, schema_editor):
    Tweet = apps.get_model("api", "Tweet")
    for tweet in Tweet.objects.filter(api_id=1):
        tweet.api_id = int(urlparse(tweet.url).path.split("/")[-1])


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="content",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="tweet",
            old_name="comments",
            new_name="pub_score",
        ),
        migrations.RemoveField(
            model_name="news",
            name="summary",
        ),
        migrations.AddField(
            model_name="news",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="image_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="api_id",
            field=models.PositiveBigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="quotes",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="replies",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="sentiment",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="reddit",
            name="sentiment",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="sentiment",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
