# Generated by Django 4.1.3 on 2022-11-17 07:20

from django.db import migrations, models

from api import services


def forward(apps, schema_editor):
    Indicator = apps.get_model("api", "Indicator")
    Stock = apps.get_model("api", "Stock")
    Indicator.objects.all().delete()
    for stock in Stock.objects.all():
        services.calculate_indices(stock)


def backward(apps, schema_editor):
    Indicator = apps.get_model("api", "Indicator")
    Indicator.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="value",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ]
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
