# Generated by Django 4.1.3 on 2022-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image_url',
            field=models.URLField(max_length=999, null=True),
        ),
    ]
