# Generated by Django 4.1.3 on 2022-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_stock_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="content",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="tweet",
            old_name="comments",
            new_name="pub_score",
        ),
        migrations.RemoveField(
            model_name="news",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="url",
        ),
        migrations.AddField(
            model_name="tweet",
            name="api_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="quotes",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="replies",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="sentiment",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reddit",
            name="sentiment",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="sentiment",
            field=models.TextField(
                choices=[
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("neutral", "Neutral"),
                ],
                null=True,
            ),
        ),
    ]
