# Generated by Django 4.1.3 on 2022-11-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_content_news_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name="reddit",
            name="url",
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="url",
            field=models.URLField(max_length=400),
        ),
    ]
