# Generated by Django 4.1.3 on 2022-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_news_url_alter_reddit_url_alter_tweet_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
