# Generated by Django 4.1.3 on 2022-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_news_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="url",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
