# Generated by Django 4.1.3 on 2022-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_indicator_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.TextField(unique=True),
        ),
    ]
