# Generated by Django 4.1.3 on 2022-11-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image_url',
            field=models.URLField(max_length=999, null=True),
        ),
    ]
