"""add reddit api id

Revision ID: 0bcb358b278a
Revises: ef3554a4abea
Create Date: 2022-10-01 00:30:12.026174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcb358b278a'
down_revision = 'ef3554a4abea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redditpost', sa.Column('api_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redditpost', 'api_id')
    # ### end Alembic commands ###
