"""standardise foreign key naming convention

Revision ID: d62a694ade35
Revises: b2e18de5e110
Create Date: 2022-10-12 13:53:42.627385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62a694ade35'
down_revision = 'b2e18de5e110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('country_id', sa.Integer(), nullable=False))
    op.drop_constraint('exchange_country_fkey', 'exchange', type_='foreignkey')
    op.create_foreign_key(None, 'exchange', 'country', ['country_id'], ['id'])
    op.drop_column('exchange', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    op.create_foreign_key('exchange_country_fkey', 'exchange', 'country', ['country'], ['id'])
    op.drop_column('exchange', 'country_id')
    # ### end Alembic commands ###
